[package]
name = "glutin"
version = "0.1.2"
authors = ["tomaka <pierre.krieger1708@gmail.com>"]
description = "Cross-plaform OpenGL context provider."
keywords = ["windowing", "opengl"]
license = "Apache-2.0"
readme = "README.md"
repository = "https://github.com/tomaka/glutin"
documentation = "http://tomaka.github.io/glutin/"
build = "build.rs"

[features]
default = ["window"]
window = []

[dependencies]
gl_common = "0.0.4"
lazy_static = "0.1.10"
libc = "0.1"
shared_library = "0.1.0"

[build-dependencies]
gl_generator = "0.0.25"
khronos_api = "0.0.5"

[dev-dependencies]
clock_ticks = "0.0.5"

[target.arm-linux-androideabi.dependencies.android_glue]
version = "0"

[target.x86_64-apple-darwin.dependencies]
objc = "0.1"
glutin_cocoa = "0"
glutin_core_graphics = "0"
glutin_core_foundation = "0"

[target.i686-pc-windows-gnu.dependencies]
winapi = "0.1"
gdi32-sys = "0.1"
user32-sys = "0.1"
kernel32-sys = "0.1"
dwmapi-sys = "0.1"

[target.x86_64-pc-windows-gnu.dependencies]
winapi = "0.1"
gdi32-sys = "0.1"
user32-sys = "0.1"
kernel32-sys = "0.1"
dwmapi-sys = "0.1"

[target.i686-unknown-linux-gnu.dependencies]
osmesa-sys = "0.0.5"
wayland-client = "0.1.3"
x11-dl = "=1.0.1"

[target.x86_64-unknown-linux-gnu.dependencies]
osmesa-sys = "0.0.5"
wayland-client = "0.1.3"
x11-dl = "=1.0.1"

[target.arm-unknown-linux-gnueabihf.dependencies]
osmesa-sys = "0.0.5"
wayland-client = "0.1.3"
x11-dl = "=1.0.1"
